### ISSUE TITLE
Do not return decode_json errors

### ISSUE THREAD

**Issue by schroeer** [graphql-perl/Mojolicious-Plugin-GraphQL#2]
If the `/graphql` endpoint is requested with an empty body (e.g. by just typing the URL into a browser), a message like this is returned:

> `{"errors":[{"message":"malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before \"(end of string)\") at \/usr\/local\/share\/perl\/5.26.1\/Mojo\/JSON.pm line 39.\n"}]}`

I think that this reveals too much unnecessary information. I'd prefer to just say that the request is malformed.

The relevant code is here: https://github.com/graphql-perl/Mojolicious-Plugin-GraphQL/blob/8db563bd84ccaa6f6ff2dafcb60903b935080941/lib/Mojolicious/Plugin/GraphQL.pm#L103-L105

**Comment by mohawk2** [comment]
Thanks, released as 0.14!
