### ISSUE TITLE
Current graphql.min.js wants react16

### ISSUE THREAD

**Issue by JForst** [graphql-perl/Mojolicious-Plugin-GraphQL#3]
showing the /graphql site for debugging in graphiql =>1 mode shows empty page.

`Error: GraphiQL 0.18.0 and after is not compatible with React 15 or below.
If you are using a CDN source (jsdelivr, unpkg, etc), follow this example:
https://github.com/graphql/graphiql/blob/master/examples/graphiql-cdn/index.html#L49`

**Comment by mohawk2** [comment]
Thanks for the PR!

**Comment by mohawk2** [comment]
Released as 0.17.
